version: '3.9'

services:
  mongodb:
    image: mongo:7.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - default

  flask:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on: 
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/HospitalDB
    networks:
      - default

volumes:
  data:
    name: data-volume

networks:
  default:
