services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    flask:
        image: flights_flask
        restart: always
        ports:
            - 5000:5000
        depends_on: 
            - mongodb    
